name: employee_leave_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  bloc_test: ^10.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/mock_data/
