name: Deploy to GitHub Pages

on:
  push:
    branches:
      - release/** # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4' # Specify the Flutter version you want to use

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --base-href="/employee_leave_manager/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
